# Generated by Django 2.2.7 on 2020-01-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=256, verbose_name='页面名称')),
                ('locate_type', models.IntegerField(default=1, verbose_name='定位方式(1:id,2:name,3:css表达式,4:xpath,5:class,6:tag，7:linktext)')),
                ('locate_partern', models.CharField(max_length=256, verbose_name='定位表达式')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='描述信息')),
            ],
        ),
        migrations.CreateModel(
            name='UiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, verbose_name='用例编号')),
                ('case_name', models.CharField(max_length=256, verbose_name='用例名称')),
                ('case_description', models.CharField(max_length=256, null=True, verbose_name='用例描述')),
                ('run_flag', models.BooleanField(default=True, verbose_name='运行标志（1运行，0禁止）')),
                ('builder', models.CharField(default='', max_length=256, null=True, verbose_name='创建人')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_manager.Module', verbose_name='所属模块')),
            ],
        ),
        migrations.CreateModel(
            name='WebParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=256, verbose_name='参数名')),
                ('param_value', models.CharField(max_length=256, verbose_name='参数值')),
                ('belong_menu', models.CharField(default='', max_length=256, null=True, verbose_name='所属菜单')),
                ('description', models.CharField(default='', max_length=256, null=True, verbose_name='描述')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UiCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=256, verbose_name='步骤名称')),
                ('type', models.IntegerField(default=1, verbose_name='步骤类型(1:操作，2:等待，3断言)')),
                ('sleep_time', models.IntegerField(default=1, null=True, verbose_name='等待时长，单位：秒')),
                ('operate_type', models.IntegerField(null=True, verbose_name='操作类型(1:点击,2:输入,3:双击,4:悬停,5:右击,6:获取值,7:获取文本，8：frame切换)')),
                ('content', models.CharField(max_length=256, null=True, verbose_name='操作内容')),
                ('asset_type', models.IntegerField(default=1, null=True, verbose_name='断言类型(1:相等2:包含3:正则)')),
                ('asset_partern', models.CharField(max_length=256, null=True, verbose_name='断言表达式')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_auto.UiCase', verbose_name='所属用例')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_auto.Element', verbose_name='对应元素')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.CharField(default='', max_length=50, null=True, verbose_name='页面编号')),
                ('page_name', models.CharField(max_length=256, verbose_name='页面名称')),
                ('builder', models.CharField(max_length=256, null=True, verbose_name='创建人')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('page_description', models.CharField(default='', max_length=256, null=True, verbose_name='描述')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_manager.Module', verbose_name='所属模块')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_auto.Page', verbose_name='所属页面'),
        ),
    ]
