# Generated by Django 2.2.7 on 2020-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uicasestep',
            name='sleep_time',
        ),
        migrations.AlterField(
            model_name='uicasestep',
            name='type',
            field=models.IntegerField(default=1, verbose_name='步骤类型(1操作，2断言)'),
        ),
    ]
