# Generated by Django 2.2.7 on 2020-01-15 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0001_initial'),
        ('web_auto', '0002_auto_20200114_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='page',
        ),
        migrations.AddField(
            model_name='element',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_manager.Module', verbose_name='所属模块'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
