# Generated by Django 2.2.7 on 2020-01-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0003_auto_20200115_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uicasestep',
            old_name='asset_partern',
            new_name='assert_partern',
        ),
        migrations.RenameField(
            model_name='uicasestep',
            old_name='asset_type',
            new_name='assert_type',
        ),
    ]
