# Generated by Django 2.2.7 on 2020-01-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0004_auto_20200115_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicasestep',
            name='assert_type',
            field=models.IntegerField(null=True, verbose_name='断言类型(1:相等2:包含3:正则)'),
        ),
    ]
