# Generated by Django 2.2.7 on 2020-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0005_auto_20200115_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicasestep',
            name='step_no',
            field=models.IntegerField(default=1, verbose_name='步骤编号'),
            preserve_default=False,
        ),
    ]
