# Generated by Django 2.2.7 on 2020-01-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0006_uicasestep_step_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicasestep',
            name='content',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='操作内容'),
        ),
    ]
