# Generated by Django 2.2.7 on 2020-01-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0007_auto_20200117_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_no', models.CharField(max_length=256, verbose_name='测试集编号')),
                ('suit_name', models.CharField(max_length=256, verbose_name='测试集名称')),
                ('suit_description', models.CharField(max_length=256, null=True, verbose_name='测试集描述')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('builder', models.CharField(max_length=256, null=True, verbose_name='创建人')),
                ('ui_case', models.ManyToManyField(to='web_auto.UiCase', verbose_name='测试用例')),
            ],
        ),
        migrations.CreateModel(
            name='UiSuitExecuteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ececute_status', models.IntegerField(default=1, verbose_name='执行状态（1未开始，2执行中，3执行结束）')),
                ('execute_person', models.CharField(max_length=256, null=True, verbose_name='执行人')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='执行开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='执行结束时间')),
                ('report_url', models.CharField(max_length=256, null=True, verbose_name='执行报告路径')),
                ('log_url', models.CharField(max_length=256, null=True, verbose_name='日志路径')),
                ('ui_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_auto.UiSuit', verbose_name='测试用例集')),
            ],
        ),
    ]
