# Generated by Django 2.2.7 on 2020-01-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0008_uisuit_uisuitexecuterecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiSuitCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=256, null=True, verbose_name='模块名称')),
                ('case_no', models.CharField(db_index=True, max_length=250, verbose_name='用例编号')),
                ('case_name', models.CharField(max_length=256, verbose_name='用例名称')),
                ('case_description', models.CharField(max_length=256, null=True, verbose_name='用例描述')),
                ('run_flag', models.BooleanField(default=True, verbose_name='运行标志（1运行，0禁止）')),
                ('element_name', models.CharField(max_length=256, verbose_name='断言元素')),
                ('assert_type', models.IntegerField(default=1, verbose_name='断言类型(1值相等，2值包含，3值正则，4文本相等，5文本包含，6文本正则)')),
                ('assert_partern', models.TextField(max_length=100000, verbose_name='断言值/表达式')),
                ('real_result', models.TextField(max_length=100000, null=True, verbose_name='断言实际值')),
                ('pass_flag', models.IntegerField(verbose_name='是否通过(1通过,2未通过，3异常)')),
                ('exception_msg', models.TextField(max_length=100000, null=True, verbose_name='异常信息')),
                ('builder', models.CharField(max_length=256, null=True, verbose_name='创建人')),
                ('build_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('start_time', models.DateTimeField(null=True, verbose_name='执行开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='执行结束时间')),
                ('ui_suit_execute_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_auto.UiSuitExecuteRecord', verbose_name='测试用例集记录')),
            ],
        ),
    ]
