# Generated by Django 2.2.7 on 2020-01-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0011_auto_20200119_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='locate_type',
            field=models.IntegerField(default=1, verbose_name='定位方式(1:id,2:name,3:css表达式,4:xpath,5:class,6:tag,7:linktext,8:frame,9:window)'),
        ),
    ]
