# Generated by Django 2.2.7 on 2020-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auto', '0012_auto_20200119_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uisuitcaseexecuterecord',
            name='pass_flag',
            field=models.IntegerField(null=True, verbose_name='是否通过(1通过,2未通过，3异常)'),
        ),
    ]
