# Generated by Django 2.2.7 on 2020-01-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0001_initial'),
        ('web_auto', '0013_auto_20200128_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='UiElement',
        ),
        migrations.RenameModel(
            old_name='WebParam',
            new_name='UiParam',
        ),
    ]
