# Generated by Django 2.2.7 on 2019-12-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0001_initial'),
        ('interface_auto', '0002_interfacecase_builder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacecase',
            old_name='product',
            new_name='module',
        ),
        migrations.AlterIndexTogether(
            name='interfacecase',
            index_together={('module', 'case_name')},
        ),
    ]
