# Generated by Django 2.2.7 on 2019-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0005_interfacesuit_interfacesuitcaseexecuterecord_interfacesuitexecuterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='asset_partern',
            field=models.TextField(max_length=100000, verbose_name='断言值/表达式'),
        ),
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='real_result',
            field=models.TextField(max_length=100000, null=True, verbose_name='实际结果'),
        ),
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='request_cookie',
            field=models.TextField(max_length=100000, null=True, verbose_name='请求cookie'),
        ),
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='request_header',
            field=models.TextField(max_length=100000, null=True, verbose_name='请求头'),
        ),
    ]
