# Generated by Django 2.2.7 on 2019-12-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0007_auto_20191224_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacesuitexecuterecord',
            name='report_url',
            field=models.CharField(max_length=50, null=True, verbose_name='执行报告路径'),
        ),
    ]
