# Generated by Django 2.2.7 on 2019-12-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0008_interfacesuitexecuterecord_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacesuitcaseexecuterecord',
            name='exception_msg',
            field=models.TextField(max_length=100000, null=True, verbose_name='异常信息'),
        ),
    ]
