# Generated by Django 2.2.7 on 2019-12-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0009_interfacesuitcaseexecuterecord_exception_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='case_no',
            field=models.CharField(db_index=True, max_length=50, verbose_name='用例编号'),
        ),
    ]
