# Generated by Django 2.2.7 on 2019-12-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0010_auto_20191230_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacesuitexecuterecord',
            name='log_url',
            field=models.CharField(max_length=50, null=True, verbose_name='日志路径'),
        ),
    ]
