# Generated by Django 2.2.7 on 2019-12-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0012_auto_20191231_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='build_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='modify_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='interfacesuitcaseexecuterecord',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='执行开始时间'),
        ),
    ]
