# Generated by Django 2.2.7 on 2020-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0014_interfacecase_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacesuitcaseexecuterecord',
            name='content_type',
            field=models.IntegerField(default=1, verbose_name='内容类型（1json，2form表单，3xml）'),
        ),
    ]
