# Generated by Django 2.2.7 on 2020-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0015_interfacesuitcaseexecuterecord_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacecase',
            old_name='asset_type',
            new_name='assert_type',
        ),
        migrations.RenameField(
            model_name='interfacesuitcaseexecuterecord',
            old_name='asset_partern',
            new_name='assert_partern',
        ),
        migrations.RenameField(
            model_name='interfacesuitcaseexecuterecord',
            old_name='asset_type',
            new_name='assert_type',
        ),
        migrations.RemoveField(
            model_name='interfacecase',
            name='asset_partern',
        ),
        migrations.RemoveField(
            model_name='interfacecase',
            name='exp_result',
        ),
        migrations.RemoveField(
            model_name='interfacesuitcaseexecuterecord',
            name='exp_result',
        ),
        migrations.AddField(
            model_name='interfacecase',
            name='assert_partern',
            field=models.TextField(max_length=100000, null=True, verbose_name='断言值/表达式'),
        ),
    ]
