# Generated by Django 2.2.7 on 2020-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0016_auto_20200108_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacesuit',
            old_name='interfaceCase',
            new_name='interface_case',
        ),
        migrations.AlterField(
            model_name='interfacesuit',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='interfacesuitexecuterecord',
            name='ececute_status',
            field=models.IntegerField(default=1, verbose_name='执行状态（1未开始，2执行中，3执行结束）'),
        ),
    ]
