# Generated by Django 2.2.7 on 2020-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_auto', '0017_auto_20200117_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacesuit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
