# Generated by Django 2.2.7 on 2019-12-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.BooleanField(default=True, verbose_name='性别（1男，0女）')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('comment', models.CharField(default='', max_length=256, null=True, verbose_name='备注')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SysParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=50, verbose_name='参数名')),
                ('param_value', models.CharField(max_length=50, verbose_name='参数值')),
                ('belong_menu', models.CharField(max_length=50, null=True, verbose_name='所属菜单')),
                ('description', models.CharField(default='', max_length=256, null=True, verbose_name='描述')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.CharField(max_length=50, verbose_name='模块编码')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名')),
                ('module_type', models.BooleanField(default=True, verbose_name='模块类型（1业务模块，0接口模块）')),
                ('module_desc', models.CharField(default='', max_length=256, null=True, verbose_name='模块描述')),
                ('manager', models.CharField(default='', max_length=50, null=True, verbose_name='负责人')),
                ('builder', models.CharField(default='', max_length=50, null=True, verbose_name='创建人')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_manager.Module', verbose_name='父模块编码')),
            ],
        ),
    ]
