# Generated by Django 2.2.7 on 2019-12-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.BooleanField(default=True, verbose_name='性别（1男，0女）')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('comment', models.CharField(default='', max_length=256, null=True, verbose_name='备注')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名')),
                ('module_type', models.BooleanField(default=True, verbose_name='模块类型（1业务模块，0接口模块）')),
                ('module_desc', models.CharField(default='', max_length=256, null=True, verbose_name='模块描述')),
                ('manager', models.CharField(default='', max_length=50, null=True, verbose_name='负责人')),
                ('builder', models.CharField(default='', max_length=50, null=True, verbose_name='创建人')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SysParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=50, verbose_name='参数名')),
                ('param_value', models.CharField(max_length=50, verbose_name='参数值')),
                ('belong_menu', models.CharField(max_length=50, null=True, verbose_name='所属菜单')),
                ('description', models.CharField(default='', max_length=256, null=True, verbose_name='描述')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(db_index=True, max_length=50, verbose_name='用例编号')),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('case_description', models.CharField(max_length=256, null=True, verbose_name='用例描述')),
                ('run_flag', models.BooleanField(default=True, verbose_name='运行标志（1运行，0禁止）')),
                ('url', models.CharField(max_length=50, verbose_name='请求地址')),
                ('request_method', models.IntegerField(default=1, verbose_name='请求方法（1get，2post）')),
                ('request_header', models.CharField(max_length=256, null=True, verbose_name='请求头')),
                ('request_cookie', models.CharField(max_length=256, null=True, verbose_name='请求cookie')),
                ('request_param', models.TextField(max_length=100000, null=True, verbose_name='请求参数')),
                ('exp_result', models.TextField(max_length=100000, verbose_name='预期结果')),
                ('asset_type', models.IntegerField(default=1, verbose_name='断言类型(1相等，2包含，3正则)')),
                ('asset_partern', models.CharField(max_length=256, null=True, verbose_name='断言表达式')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_manager.Module', verbose_name='所属模块')),
            ],
            options={
                'index_together': {('product_id', 'case_name')},
            },
        ),
    ]
