# Generated by Django 2.2.7 on 2019-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
