# Generated by Django 2.2.7 on 2019-12-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageruser',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='gender',
            field=models.BooleanField(null=True),
        ),
    ]
