# Generated by Django 2.2.7 on 2020-02-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, verbose_name='任务编号')),
                ('task_name', models.CharField(max_length=50, verbose_name='任务名')),
                ('task_type', models.IntegerField(max_length=1, verbose_name='任务类型（1：接口任务，2：UI任务）')),
                ('task_desc', models.CharField(max_length=256, null=True, verbose_name='任务描述')),
                ('task_partern', models.CharField(max_length=256, null=True, verbose_name='任务定时表达式')),
                ('run_flag', models.BooleanField(default=True, verbose_name='运行标志（1是，0否）')),
                ('manager', models.CharField(max_length=50, null=True, verbose_name='负责人')),
                ('builder', models.CharField(max_length=50, null=True, verbose_name='创建人')),
                ('build_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('suit_id', models.IntegerField(verbose_name='用例集id')),
            ],
        ),
    ]
