# Generated by Django 2.2.7 on 2020-02-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(verbose_name='任务类型（1：接口任务，2：UI任务）'),
        ),
    ]
