# Generated by Django 2.2.7 on 2019-12-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0002_module_module_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='parent_module_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_manager.Module', verbose_name='父模块编码'),
        ),
    ]
