# Generated by Django 2.2.7 on 2020-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manager', '0003_auto_20200202_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='builder',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='任务描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_partern',
            field=models.CharField(default='', max_length=256, verbose_name='任务定时表达式'),
            preserve_default=False,
        ),
    ]
